class FindCharacterDiff:

    # String t is generated by random shuffling string s and then add one more letter at a random position.
    # Return the letter that was added to t.
    
    def findTheDifference(self, s: str, t: str) -> str:
        int_s = sum(ord(c) for c in s)
        int_t = sum(ord(c) for c in t)
        result = abs(int_t - int_s)
        return chr(result)
    
"""
Time Complexity:

sum(ord(c) for c in s)  > O(n)
sum(ord(c) for c in t)  > O(n+1)
abs(int_t - int_s)      > O(1)
chr(result)             > O(1)

Total: O(n) + O(n+1) + O(1) + O(1) = O(n)

Space Complexity:

not creating any data structures
just few arithmatic operations
O(1)

"""